[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "7436581bc68ca207a6067f722b76638a1c659787"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "d3ef59b9cf2a1b2a148e1f683bea5c07260f77adc6b8b498ec6ec9daae616d1f"
    url = "https://github.com/boriskaus/PETSc_jll1.jl/releases/download/PETSc-v3.24.2+0/PETSc.v3.24.2.aarch64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "98e770a0b74a73a98f685deac67b5ddca7d68e3a"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[PETSc.download]]
    sha256 = "204c91734c6a8e3b1593208b5fc85db12a8a209a7bdde86658ed8f8956b53133"
    url = "https://github.com/boriskaus/PETSc_jll1.jl/releases/download/PETSc-v3.24.2+0/PETSc.v3.24.2.x86_64-linux-gnu-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "0a265f64ce9bdde567959a2ed8bf5fc3cf5f5dd4"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "macos"

    [[PETSc.download]]
    sha256 = "be65de52191aa1cd612b8484719100064ebbcf0b7a292827043b6135832f8ab7"
    url = "https://github.com/boriskaus/PETSc_jll1.jl/releases/download/PETSc-v3.24.6+0/PETSc.v3.24.6.x86_64-apple-darwin-libgfortran5-mpi+mpich.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d348328fa764bb9032412d192e8d1bc4c39c11c9"
libgfortran_version = "5.0.0"
mpi = "microsoftmpi"
os = "windows"

    [[PETSc.download]]
    sha256 = "e002998bae108f59f842c5bb3a316798e35883258cde33306326e86c6a8c5b7a"
    url = "https://github.com/boriskaus/PETSc_jll1.jl/releases/download/PETSc-v3.24.6+0/PETSc.v3.24.6.x86_64-w64-mingw32-libgfortran5-mpi+microsoftmpi.tar.gz"
