# Autogenerated wrapper script for PETSc_jll for x86_64-apple-darwin-libgfortran5-mpi+mpich
export ex19, ex19_int32, ex19_int64_deb, ex4, ex42, libpetsc, libpetsc_Float32_Complex_Int32, libpetsc_Float32_Complex_Int64, libpetsc_Float32_Real_Int32, libpetsc_Float32_Real_Int64, libpetsc_Float64_Complex_Int32, libpetsc_Float64_Complex_Int64, libpetsc_Float64_Real_Int32, libpetsc_Float64_Real_Int64, libpetsc_Float64_Real_Int64_deb

using CompilerSupportLibraries_jll
using libblastrampoline_jll
using MUMPS_jll
using OpenBLAS32_jll
using HYPRE64_jll
using HYPRE_jll
using SuperLU_DIST_jll
using TetGen_jll
using Triangle_jll
using SuiteSparse_jll
using MPICH_jll
JLLWrappers.@generate_wrapper_header("PETSc")
JLLWrappers.@declare_library_product(libpetsc, "@rpath/libpetsc_double_real_Int64.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float32_Complex_Int32, "@rpath/libpetsc_single_complex_Int32.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float32_Complex_Int64, "@rpath/libpetsc_single_complex_Int64.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float32_Real_Int32, "@rpath/libpetsc_single_real_Int32.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float32_Real_Int64, "@rpath/libpetsc_single_real_Int64.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float64_Complex_Int32, "@rpath/libpetsc_double_complex_Int32.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float64_Complex_Int64, "@rpath/libpetsc_double_complex_Int64.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int32, "@rpath/libpetsc_double_real_Int32.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64, "@rpath/libpetsc_double_real_Int64.3.25.dylib")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64_deb, "@rpath/libpetsc_double_real_Int64_deb.3.25.dylib")
JLLWrappers.@declare_executable_product(ex19)
JLLWrappers.@declare_executable_product(ex19_int32)
JLLWrappers.@declare_executable_product(ex19_int64_deb)
JLLWrappers.@declare_executable_product(ex4)
JLLWrappers.@declare_executable_product(ex42)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, libblastrampoline_jll, MUMPS_jll, OpenBLAS32_jll, HYPRE64_jll, HYPRE_jll, SuperLU_DIST_jll, TetGen_jll, Triangle_jll, SuiteSparse_jll, MPICH_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libpetsc,
        "lib/petsc/double_real_Int64/lib/libpetsc_double_real_Int64.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Complex_Int32,
        "lib/petsc/single_complex_Int32/lib/libpetsc_single_complex_Int32.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Complex_Int64,
        "lib/petsc/single_complex_Int64/lib/libpetsc_single_complex_Int64.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Real_Int32,
        "lib/petsc/single_real_Int32/lib/libpetsc_single_real_Int32.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Real_Int64,
        "lib/petsc/single_real_Int64/lib/libpetsc_single_real_Int64.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Complex_Int32,
        "lib/petsc/double_complex_Int32/lib/libpetsc_double_complex_Int32.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Complex_Int64,
        "lib/petsc/double_complex_Int64/lib/libpetsc_double_complex_Int64.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int32,
        "lib/petsc/double_real_Int32/lib/libpetsc_double_real_Int32.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64,
        "lib/petsc/double_real_Int64/lib/libpetsc_double_real_Int64.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64_deb,
        "lib/petsc/double_real_Int64_deb/lib/libpetsc_double_real_Int64_deb.3.25.4.dylib",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        ex19,
        "bin/ex19",
    )

    JLLWrappers.@init_executable_product(
        ex19_int32,
        "bin/ex19_int32",
    )

    JLLWrappers.@init_executable_product(
        ex19_int64_deb,
        "bin/ex19_int64_deb",
    )

    JLLWrappers.@init_executable_product(
        ex4,
        "bin/ex4",
    )

    JLLWrappers.@init_executable_product(
        ex42,
        "bin/ex42",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
