# Autogenerated wrapper script for PETSc_jll for x86_64-w64-mingw32-libgfortran5-cxx11-mpi+microsoftmpi
export ex19, ex19_int32, ex19_int64_deb, ex4, ex42, libpetsc, libpetsc_Float32_Complex_Int32, libpetsc_Float32_Complex_Int64, libpetsc_Float32_Real_Int32, libpetsc_Float32_Real_Int64, libpetsc_Float64_Complex_Int32, libpetsc_Float64_Complex_Int64, libpetsc_Float64_Real_Int32, libpetsc_Float64_Real_Int64, libpetsc_Float64_Real_Int64_deb

using CompilerSupportLibraries_jll
using OpenBLAS_jll
using MUMPS_jll
using OpenBLAS32_jll
using HYPRE_jll
using SuperLU_DIST_jll
using TetGen_jll
using Triangle_jll
using SuiteSparse_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("PETSc")
JLLWrappers.@declare_library_product(libpetsc, "libpetsc_double_real_Int64-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float32_Complex_Int32, "libpetsc_single_complex_Int32-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float32_Complex_Int64, "libpetsc_single_complex_Int64-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float32_Real_Int32, "libpetsc_single_real_Int32-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float32_Real_Int64, "libpetsc_single_real_Int64-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float64_Complex_Int32, "libpetsc_double_complex_Int32-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float64_Complex_Int64, "libpetsc_double_complex_Int64-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int32, "libpetsc_double_real_Int32-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64, "libpetsc_double_real_Int64-3.25.4.dll")
JLLWrappers.@declare_library_product(libpetsc_Float64_Real_Int64_deb, "libpetsc_double_real_Int64_deb-3.25.4.dll")
JLLWrappers.@declare_executable_product(ex19)
JLLWrappers.@declare_executable_product(ex19_int32)
JLLWrappers.@declare_executable_product(ex19_int64_deb)
JLLWrappers.@declare_executable_product(ex4)
JLLWrappers.@declare_executable_product(ex42)
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, OpenBLAS_jll, MUMPS_jll, OpenBLAS32_jll, HYPRE_jll, SuperLU_DIST_jll, TetGen_jll, Triangle_jll, SuiteSparse_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libpetsc,
        "bin\\petsc\\double_real_Int64\\lib\\libpetsc_double_real_Int64-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Complex_Int32,
        "bin\\petsc\\single_complex_Int32\\lib\\libpetsc_single_complex_Int32-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Complex_Int64,
        "bin\\petsc\\single_complex_Int64\\lib\\libpetsc_single_complex_Int64-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Real_Int32,
        "bin\\petsc\\single_real_Int32\\lib\\libpetsc_single_real_Int32-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float32_Real_Int64,
        "bin\\petsc\\single_real_Int64\\lib\\libpetsc_single_real_Int64-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Complex_Int32,
        "bin\\petsc\\double_complex_Int32\\lib\\libpetsc_double_complex_Int32-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Complex_Int64,
        "bin\\petsc\\double_complex_Int64\\lib\\libpetsc_double_complex_Int64-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int32,
        "bin\\petsc\\double_real_Int32\\lib\\libpetsc_double_real_Int32-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64,
        "bin\\petsc\\double_real_Int64\\lib\\libpetsc_double_real_Int64-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_library_product(
        libpetsc_Float64_Real_Int64_deb,
        "bin\\petsc\\double_real_Int64_deb\\lib\\libpetsc_double_real_Int64_deb-3.25.4.dll",
        nothing,
    )

    JLLWrappers.@init_executable_product(
        ex19,
        "bin\\ex19.exe",
    )

    JLLWrappers.@init_executable_product(
        ex19_int32,
        "bin\\ex19_int32.exe",
    )

    JLLWrappers.@init_executable_product(
        ex19_int64_deb,
        "bin\\ex19_int64_deb.exe",
    )

    JLLWrappers.@init_executable_product(
        ex4,
        "bin\\ex4.exe",
    )

    JLLWrappers.@init_executable_product(
        ex42,
        "bin\\ex42.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
